### ISSUE TITLE
Print snapshot

### ISSUE THREAD

**Issue by pgs-mhans** [PGS-dev/technology-radar-ui#12]
We need possibility to render radar ready to print.

On print should be visible only:
* radar name
* snapshot name
* radar chart with blips

**Comment by amortka** [comment]
Could be simple function for downloading png or embed whole SVG as single element, something similar to https://codepen.io/amortka/pen/RRgdob?editors=1010

In order to download SVG:
```javascript
 var url = "data:image/svg+xml;charset=utf-8," + encodeURIComponent(source);

  var downloadLink = document.createElement("a");
  downloadLink.href = url;
  downloadLink.download = "radar.svg";
  document.body.appendChild(downloadLink);
  downloadLink.click();
  document.body.removeChild(downloadLink);
```

**Comment by whtrbit** [comment]
Moved to Jira board.
