### ISSUE TITLE
urlencode blib name in backend endpoint path

### ISSUE THREAD

**Issue by krzyszt0fd** [PGS-dev/technology-radar-ui#16]
In one of the radars radar we have a blip named 'C#7'. Some backend endpoints use blip name as a part of the path. In result blip name becomes C and #7 is ignored by backend since it is a legal url fragment. Blip names in urls must be encoded.
![image](https://user-images.githubusercontent.com/16668075/31166668-d9c39a28-a8ef-11e7-9e48-116f0f97f2d8.png)

**Comment by whtrbit** [comment]
Moved to Jira board.
