### ISSUE TITLE
Display comments in blip history

### ISSUE THREAD

**Issue by krzyszt0fd** [PGS-dev/technology-radar-ui#17]
Notes made on google sheet cells containing blip status should be displayed as a comments in blip history.
![image](https://user-images.githubusercontent.com/16668075/31167004-f07921ce-a8f0-11e7-8967-09bfb41751db.png)
![image](https://user-images.githubusercontent.com/16668075/31167043-06109850-a8f1-11e7-959c-63ce63f2d6a4.png)

**Comment by whtrbit** [comment]
Moved to Jira board.
