### ISSUE TITLE
BA radar

### ISSUE THREAD

**Issue by krzyszt0fd** [PGS-dev/technology-radar-ui#20]
Please put a link to BA radar on the sample radars list. 
The sheet ID is 1hVJMnhZ8IMsMAOGkxm0PwE-NIrE1korWXaN0ol_mUCQ.

**Comment by whtrbit** [comment]
Done in https://github.com/PGS-dev/technology-radar-ui/commit/5dd1bf1968a34fbec792b97910b9c83440860997
